import { GlideDateTime, GlideRecord, gs } from '@servicenow/glide'

/**
 * Business rule bodies for Cluckworks. Each exported function becomes the
 * body of a sys_script record generated by Fluent.
 */

// ---------- Bird age calculation ----------

/**
 * Before-save: if hatched_date is set, compute age_days from it.
 * Runs on bird table.
 */
export function calculateBirdAge(current: GlideRecord) {
    const hatched = current.getValue('hatched_date')
    if (!hatched) return
    const hatchedGdt = new GlideDateTime(hatched + ' 00:00:00')
    const now = new GlideDateTime()
    const ms = now.getNumericValue() - hatchedGdt.getNumericValue()
    const days = Math.floor(ms / 1000 / 60 / 60 / 24)
    current.setValue('age_days', Math.max(0, days))

    // If bird is older than 20 weeks and still marked "pullet", promote to hen
    if (current.getValue('sex') === 'pullet' && days >= 140) {
        current.setValue('sex', 'hen')
    }
    if (current.getValue('sex') === 'cockerel' && days >= 140) {
        current.setValue('sex', 'rooster')
    }
}

// ---------- Egg log: derive production rate + lifetime totals ----------

/**
 * Before-save on egg_log: compute production_rate_pct = collected / flock.current_count.
 * After-save: increment bird.lifetime_eggs for adopted hens (rough proration).
 */
export function onEggLogSave(current: GlideRecord) {
    const flockId = current.getValue('flock')
    const collected = parseInt(current.getValue('count_collected'), 10) || 0
    if (flockId && collected > 0) {
        const flock = new GlideRecord('x_1939459_cluck_flock')
        if (flock.get(flockId)) {
            const count = parseInt(flock.getValue('current_count'), 10) || 0
            if (count > 0) {
                const rate = (collected / count) * 100
                current.setValue('production_rate_pct', Math.round(rate * 10) / 10)
            }
        }
    }
}

// ---------- Feed decrement + reorder trigger ----------

/**
 * After-save on feed: if on_hand_bags drops below reorder_threshold, open
 * a reorder task (as an incident with type=other) assigned to farmer role.
 */
export function checkFeedReorder(current: GlideRecord) {
    const onHand = parseInt(current.getValue('on_hand_bags'), 10) || 0
    const threshold = parseInt(current.getValue('reorder_threshold'), 10) || 0
    const previous = parseInt((current as any).getPreviousValue?.('on_hand_bags') || String(onHand + 1), 10)

    // Only fire when crossing the threshold downward (avoid spam)
    if (onHand <= threshold && previous > threshold) {
        const inc = new GlideRecord('x_1939459_cluck_incident')
        inc.initialize()
        inc.setValue('incident_type', 'other')
        inc.setValue('severity', 'minor')
        inc.setValue('short_description', 'Feed reorder needed: ' + current.getValue('name'))
        inc.setValue(
            'evidence_notes',
            'Feed "' + current.getValue('name') + '" is at ' + onHand +
                ' bags (threshold ' + threshold + '). Supplier: ' +
                (current.getValue('supplier') || 'n/a') +
                '. Suggested reorder qty: ' + current.getValue('reorder_quantity') + ' bags.'
        )
        inc.setValue('estimated_cost',
            (parseInt(current.getValue('reorder_quantity'), 10) || 0) *
            (parseFloat(current.getValue('cost_per_bag')) || 0))
        inc.insert()
        gs.addInfoMessage('Reorder task opened for ' + current.getValue('name'))
    }
}

// ---------- Order pricing ----------

const EGG_PRICE_BY_GRADE: { [key: string]: number } = {
    jumbo: 9.5,
    xlarge: 8.5,
    large: 7.5,
    medium: 6.5,
    mixed: 8,
}

const DELIVERY_FEE: { [key: string]: number } = {
    pickup: 0,
    farm_stand: 0,
    farmers_market: 0,
    local_delivery: 5,
}

/**
 * Before-save on order: compute subtotal + total from the order type and line fields.
 */
export function calculateOrderTotal(current: GlideRecord) {
    const type = current.getValue('order_type') || 'eggs'
    let subtotal = 0

    if (type === 'eggs') {
        const dozens = parseInt(current.getValue('egg_dozens'), 10) || 0
        const grade = current.getValue('egg_grade') || 'large'
        subtotal = dozens * (EGG_PRICE_BY_GRADE[grade] || 7.5)
    } else if (type === 'chicks') {
        const qty = parseInt(current.getValue('chick_quantity'), 10) || 0
        subtotal = qty * 6 // $6/chick baseline
    } else if (type === 'tour') {
        const party = parseInt(current.getValue('tour_party_size'), 10) || 1
        const base = party * 15
        const hunt = current.getValue('tour_add_egg_hunt') === 'true' ? party * 10 : 0
        subtotal = base + hunt
    } else if (type === 'adoption') {
        subtotal = 120 // annual sponsorship
    }

    const delivery = current.getValue('delivery_type') || 'pickup'
    const fee = DELIVERY_FEE[delivery] || 0
    const discount = parseFloat(current.getValue('discount')) || 0

    current.setValue('subtotal', subtotal)
    current.setValue('delivery_fee', fee)
    current.setValue('total', Math.max(0, subtotal + fee - discount))
}

/**
 * After-save on order (fulfillment_status=delivered|picked_up):
 * award loyalty eggs (1 loyalty-egg per $1 spent) and stamp customer's
 * last_order_date + lifetime_spend.
 */
export function onOrderFulfilled(current: GlideRecord) {
    const status = current.getValue('fulfillment_status')
    if (status !== 'delivered' && status !== 'picked_up') return
    const customerId = current.getValue('customer')
    if (!customerId) return

    const total = parseFloat(current.getValue('total')) || 0
    const earned = Math.floor(total)
    current.setValue('loyalty_earned', earned)

    const cust = new GlideRecord('x_1939459_cluck_customer')
    if (cust.get(customerId)) {
        const spend = parseFloat(cust.getValue('lifetime_spend')) || 0
        const points = parseInt(cust.getValue('loyalty_eggs'), 10) || 0
        cust.setValue('lifetime_spend', spend + total)
        cust.setValue('loyalty_eggs', points + earned)
        const todayStr = String(new GlideDateTime().getDate())
        cust.setValue('last_order_date', todayStr)
        if (!cust.getValue('first_order_date')) {
            cust.setValue('first_order_date', todayStr)
        }
        cust.update()
    }
}

// ---------- Incident escalation ----------

/**
 * Before-save on incident: if severity=critical, set priority=1 and urgency=1
 * so it shows up at the top of the task list.
 */
export function escalateCriticalIncident(current: GlideRecord) {
    const sev = current.getValue('severity')
    if (sev === 'critical') {
        current.setValue('priority', '1')
        current.setValue('urgency', '1')
        current.setValue('impact', '1')
    } else if (sev === 'major') {
        current.setValue('priority', '2')
        current.setValue('urgency', '2')
    }
}

// ---------- Flock head count adjustment ----------

/**
 * After bird status changes to deceased/processed/escaped/retired, decrement
 * the flock's current_count.
 */
export function adjustFlockHeadCount(current: GlideRecord) {
    const status = current.getValue('status')
    const prev = (current as any).getPreviousValue?.('status')
    const removedStatuses = ['deceased', 'processed', 'escaped', 'retired']
    if (
        removedStatuses.indexOf(status) >= 0 &&
        removedStatuses.indexOf(prev) < 0
    ) {
        const flockId = current.getValue('flock')
        if (flockId) {
            const flock = new GlideRecord('x_1939459_cluck_flock')
            if (flock.get(flockId)) {
                const count = parseInt(flock.getValue('current_count'), 10) || 0
                flock.setValue('current_count', Math.max(0, count - 1))
                flock.update()
            }
        }
    }
}
