import { Record } from '@servicenow/sdk/core'

/**
 * Cluckworks "Meet the Flock" page layout.
 * Wires the meet-the-flock widget into a one-column page that the
 * /cluck portal homepages to.
 *
 * Cross-record references use Now.ref('<table>', '<alias>') for records
 * indexed by alias in the explicit keys section (sp_container, sp_row,
 * sp_column, sp_widget). Passing Now.ID['<alias>'] in a data field does NOT
 * resolve and ships as the raw alias literal — always use Now.ref.
 *
 * sp_page records are special: the SDK indexes them by their `id` natural
 * key, not by alias. Now.ref('sp_page', '<id>') returns the id string, not
 * the sys_id. The sp_container.sp_page reference needs the sys_id, so we
 * hard-code the deterministic sys_id the SDK derives from the alias hash
 * (visible in src/fluent/generated/keys.ts after a build).
 */

// Deterministic sys_id for sp_page_cluck_flock — generated by Now.ID hash of
// the alias 'sp_page_cluck_flock'. Stable as long as the alias name doesn't
// change. If you rename the page alias, regenerate by checking keys.ts after
// a clean build.
const PAGE_SYS_ID = '74a1ea2fc0b94591aaeb7a1f47cb9a86'

export const cluckFlockPage = Record({
    $id: Now.ID['sp_page_cluck_flock'],
    table: 'sp_page',
    data: {
        category: 'custom',
        draft: false,
        id: 'cluck_flock',
        internal: false,
        omit_watcher: false,
        public: true,
        title: 'Meet the Flock',
        use_seo_script: false,
    },
})

export const cluckFlockContainer = Record({
    $id: Now.ID['sp_container_cluck_flock'],
    table: 'sp_container',
    data: {
        background_style: 'default',
        bootstrap_alt: false,
        name: 'cluck_flock - container',
        order: 1,
        sp_page: PAGE_SYS_ID,
        subheader: false,
        width: 'container-fluid',
    },
})

export const cluckFlockRow = Record({
    $id: Now.ID['sp_row_cluck_flock'],
    table: 'sp_row',
    data: {
        order: 1,
        sp_container: Now.ref('sp_container', 'sp_container_cluck_flock'),
    },
})

export const cluckFlockColumn = Record({
    $id: Now.ID['sp_column_cluck_flock'],
    table: 'sp_column',
    data: {
        order: 1,
        size: 12,
        sp_row: Now.ref('sp_row', 'sp_row_cluck_flock'),
    },
})

export const cluckFlockInstance = Record({
    $id: Now.ID['sp_instance_cluck_flock'],
    table: 'sp_instance',
    data: {
        active: true,
        order: 1,
        sp_column: Now.ref('sp_column', 'sp_column_cluck_flock'),
        sp_widget: Now.ref('sp_widget', 'widget_meet_flock'),
    },
})
