import { Record } from '@servicenow/sdk/core'

/**
 * Starter fleet — 22 rentable items across 7 categories. Quantities and rates
 * are tuned so a small business could realistically run with this setup.
 */

// ---------- Shade & Seating ----------
Record({
    $id: Now.ID['eq_umbrella_7ft'],
    table: 'x_1939459_shorelin_equipment',
    data: {
        name: '7ft Beach Umbrella',
        sku: 'UMB-7FT',
        category: Now.ID['cat_shade_seating'],
        location: Now.ID['loc_main_pier'],
        description: '7-foot UPF 50+ umbrella with sand anchor and tilt.',
        total_quantity: 20,
        available_quantity: 20,
        hourly_rate: 4,
        half_day_rate: 10,
        full_day_rate: 15,
        weekly_rate: 60,
        deposit: 20,
        replacement_cost: 75,
        condition: 'good',
        weather_sensitive: true,
        featured: true,
    },
})
Record({
    $id: Now.ID['eq_chair_standard'],
    table: 'x_1939459_shorelin_equipment',
    data: {
        name: 'Classic Beach Chair',
        sku: 'CHR-STD',
        category: Now.ID['cat_shade_seating'],
        location: Now.ID['loc_main_pier'],
        description: 'Low-profile folding chair with cup holder.',
        total_quantity: 40,
        available_quantity: 40,
        hourly_rate: 2,
        half_day_rate: 6,
        full_day_rate: 10,
        weekly_rate: 40,
        deposit: 10,
        replacement_cost: 40,
        condition: 'good',
        featured: true,
    },
})
Record({
    $id: Now.ID['eq_cabana'],
    table: 'x_1939459_shorelin_equipment',
    data: {
        name: 'Pop-Up Cabana',
        sku: 'CAB-POP',
        category: Now.ID['cat_shade_seating'],
        location: Now.ID['loc_north_cove'],
        description: 'Four-person pop-up cabana with privacy side walls.',
        total_quantity: 8,
        available_quantity: 8,
        half_day_rate: 25,
        full_day_rate: 40,
        weekly_rate: 180,
        deposit: 50,
        replacement_cost: 220,
        condition: 'good',
        weather_sensitive: true,
    },
})

// ---------- Water Sports ----------
Record({
    $id: Now.ID['eq_surfboard_foam'],
    table: 'x_1939459_shorelin_equipment',
    data: {
        name: '8ft Foam Surfboard',
        sku: 'SRF-FOAM-8',
        category: Now.ID['cat_water_sports'],
        location: Now.ID['loc_south_jetty'],
        description: 'Beginner-friendly 8ft soft-top with leash.',
        total_quantity: 12,
        available_quantity: 12,
        hourly_rate: 12,
        half_day_rate: 25,
        full_day_rate: 40,
        weekly_rate: 180,
        deposit: 60,
        replacement_cost: 350,
        condition: 'good',
        requires_waiver: true,
        featured: true,
    },
})
Record({
    $id: Now.ID['eq_boogie_board'],
    table: 'x_1939459_shorelin_equipment',
    data: {
        name: 'Boogie Board',
        sku: 'BGY-42',
        category: Now.ID['cat_water_sports'],
        location: Now.ID['loc_main_pier'],
        description: '42-inch bodyboard for all skill levels.',
        total_quantity: 25,
        available_quantity: 25,
        hourly_rate: 5,
        half_day_rate: 10,
        full_day_rate: 15,
        weekly_rate: 70,
        deposit: 15,
        replacement_cost: 60,
        condition: 'good',
    },
})
Record({
    $id: Now.ID['eq_sup'],
    table: 'x_1939459_shorelin_equipment',
    data: {
        name: 'Stand-Up Paddleboard',
        sku: 'SUP-11',
        category: Now.ID['cat_water_sports'],
        location: Now.ID['loc_south_jetty'],
        description: '11ft inflatable SUP with paddle, leash, and pump.',
        total_quantity: 10,
        available_quantity: 10,
        hourly_rate: 15,
        half_day_rate: 30,
        full_day_rate: 50,
        weekly_rate: 220,
        deposit: 80,
        replacement_cost: 700,
        condition: 'good',
        requires_waiver: true,
    },
})
Record({
    $id: Now.ID['eq_kayak_single'],
    table: 'x_1939459_shorelin_equipment',
    data: {
        name: 'Single Kayak',
        sku: 'KYK-1',
        category: Now.ID['cat_water_sports'],
        location: Now.ID['loc_south_jetty'],
        description: 'Sit-on-top single kayak with paddle and PFD.',
        total_quantity: 6,
        available_quantity: 6,
        hourly_rate: 18,
        half_day_rate: 35,
        full_day_rate: 60,
        deposit: 100,
        replacement_cost: 900,
        condition: 'good',
        requires_waiver: true,
    },
})
Record({
    $id: Now.ID['eq_kayak_double'],
    table: 'x_1939459_shorelin_equipment',
    data: {
        name: 'Tandem Kayak',
        sku: 'KYK-2',
        category: Now.ID['cat_water_sports'],
        location: Now.ID['loc_south_jetty'],
        description: 'Sit-on-top tandem kayak with 2 paddles and 2 PFDs.',
        total_quantity: 4,
        available_quantity: 4,
        hourly_rate: 25,
        half_day_rate: 50,
        full_day_rate: 85,
        deposit: 120,
        replacement_cost: 1200,
        condition: 'good',
        requires_waiver: true,
    },
})
Record({
    $id: Now.ID['eq_snorkel_set'],
    table: 'x_1939459_shorelin_equipment',
    data: {
        name: 'Snorkel Set',
        sku: 'SNK-SET',
        category: Now.ID['cat_water_sports'],
        location: Now.ID['loc_main_pier'],
        description: 'Mask, snorkel, and fins. Sanitized between rentals.',
        total_quantity: 18,
        available_quantity: 18,
        hourly_rate: 6,
        half_day_rate: 12,
        full_day_rate: 18,
        weekly_rate: 80,
        deposit: 20,
        replacement_cost: 75,
        condition: 'good',
    },
})
Record({
    $id: Now.ID['eq_wetsuit'],
    table: 'x_1939459_shorelin_equipment',
    data: {
        name: '3/2mm Wetsuit',
        sku: 'WET-32',
        category: Now.ID['cat_water_sports'],
        location: Now.ID['loc_south_jetty'],
        description: 'Full-body 3/2mm wetsuit. Sizes S–XL.',
        total_quantity: 15,
        available_quantity: 15,
        hourly_rate: 8,
        half_day_rate: 15,
        full_day_rate: 25,
        weekly_rate: 100,
        deposit: 30,
        replacement_cost: 180,
        condition: 'good',
    },
})

// ---------- Beach Essentials ----------
Record({
    $id: Now.ID['eq_towel'],
    table: 'x_1939459_shorelin_equipment',
    data: {
        name: 'Oversized Beach Towel',
        sku: 'TWL-XL',
        category: Now.ID['cat_essentials'],
        location: Now.ID['loc_main_pier'],
        description: 'Oversized microfiber towel, fresh laundered.',
        total_quantity: 80,
        available_quantity: 80,
        full_day_rate: 5,
        weekly_rate: 20,
        deposit: 0,
        replacement_cost: 25,
        condition: 'new',
    },
})
Record({
    $id: Now.ID['eq_cooler'],
    table: 'x_1939459_shorelin_equipment',
    data: {
        name: '24-Can Cooler',
        sku: 'COOL-24',
        category: Now.ID['cat_essentials'],
        location: Now.ID['loc_main_pier'],
        description: '24-can soft cooler with shoulder strap. Ice upgrade $5.',
        total_quantity: 15,
        available_quantity: 15,
        hourly_rate: 3,
        half_day_rate: 6,
        full_day_rate: 10,
        weekly_rate: 40,
        deposit: 15,
        replacement_cost: 60,
        condition: 'good',
    },
})
Record({
    $id: Now.ID['eq_wagon'],
    table: 'x_1939459_shorelin_equipment',
    data: {
        name: 'Heavy-Duty Beach Wagon',
        sku: 'WGN-HD',
        category: Now.ID['cat_essentials'],
        location: Now.ID['loc_main_pier'],
        description: 'Collapsible beach wagon. Hauls 200 lbs over sand.',
        total_quantity: 12,
        available_quantity: 12,
        hourly_rate: 5,
        half_day_rate: 12,
        full_day_rate: 18,
        weekly_rate: 70,
        deposit: 30,
        replacement_cost: 180,
        condition: 'good',
        featured: true,
    },
})
Record({
    $id: Now.ID['eq_yoga_mat'],
    table: 'x_1939459_shorelin_equipment',
    data: {
        name: 'Beach Yoga Mat',
        sku: 'YGA-MAT',
        category: Now.ID['cat_essentials'],
        location: Now.ID['loc_north_cove'],
        description: 'Sand-resistant yoga mat.',
        total_quantity: 20,
        available_quantity: 20,
        full_day_rate: 8,
        weekly_rate: 35,
        deposit: 10,
        replacement_cost: 50,
        condition: 'good',
    },
})
Record({
    $id: Now.ID['eq_baby_tent'],
    table: 'x_1939459_shorelin_equipment',
    data: {
        name: 'Baby Sun Tent',
        sku: 'BBY-TNT',
        category: Now.ID['cat_essentials'],
        location: Now.ID['loc_main_pier'],
        description: 'UPF 50+ pop-up tent for infants and toddlers.',
        total_quantity: 10,
        available_quantity: 10,
        half_day_rate: 8,
        full_day_rate: 12,
        weekly_rate: 50,
        deposit: 15,
        replacement_cost: 80,
        condition: 'good',
    },
})

// ---------- Games & Kids ----------
Record({
    $id: Now.ID['eq_volleyball'],
    table: 'x_1939459_shorelin_equipment',
    data: {
        name: 'Volleyball Set (net + ball)',
        sku: 'VOL-SET',
        category: Now.ID['cat_games'],
        location: Now.ID['loc_main_pier'],
        description: 'Portable volleyball net, posts, ball, and pump.',
        total_quantity: 6,
        available_quantity: 6,
        half_day_rate: 10,
        full_day_rate: 15,
        deposit: 25,
        replacement_cost: 120,
        condition: 'good',
    },
})
Record({
    $id: Now.ID['eq_spikeball'],
    table: 'x_1939459_shorelin_equipment',
    data: {
        name: 'Spikeball / Roundnet Set',
        sku: 'SPK-SET',
        category: Now.ID['cat_games'],
        location: Now.ID['loc_main_pier'],
        description: 'Spikeball roundnet with 2 balls.',
        total_quantity: 8,
        available_quantity: 8,
        half_day_rate: 6,
        full_day_rate: 10,
        deposit: 15,
        replacement_cost: 70,
        condition: 'good',
    },
})
Record({
    $id: Now.ID['eq_sand_toys'],
    table: 'x_1939459_shorelin_equipment',
    data: {
        name: 'Sand Toy Bucket (kids)',
        sku: 'KID-TOYS',
        category: Now.ID['cat_games'],
        location: Now.ID['loc_main_pier'],
        description: 'Bucket, shovel, castle molds, rakes.',
        total_quantity: 20,
        available_quantity: 20,
        full_day_rate: 6,
        deposit: 5,
        replacement_cost: 25,
        condition: 'good',
    },
})
Record({
    $id: Now.ID['eq_kite'],
    table: 'x_1939459_shorelin_equipment',
    data: {
        name: 'Beach Kite Kit',
        sku: 'KIT-DLT',
        category: Now.ID['cat_games'],
        location: Now.ID['loc_north_cove'],
        description: 'Easy-fly delta kite with 500ft line.',
        total_quantity: 10,
        available_quantity: 10,
        full_day_rate: 8,
        deposit: 10,
        replacement_cost: 45,
        condition: 'good',
    },
})

// ---------- Tech & Tunes ----------
Record({
    $id: Now.ID['eq_speaker'],
    table: 'x_1939459_shorelin_equipment',
    data: {
        name: 'Waterproof Bluetooth Speaker',
        sku: 'SPK-BT',
        category: Now.ID['cat_tech'],
        location: Now.ID['loc_main_pier'],
        description: 'Rugged waterproof speaker, 12-hour battery.',
        total_quantity: 8,
        available_quantity: 8,
        hourly_rate: 4,
        half_day_rate: 10,
        full_day_rate: 15,
        deposit: 40,
        replacement_cost: 150,
        condition: 'good',
        featured: true,
    },
})
Record({
    $id: Now.ID['eq_gopro'],
    table: 'x_1939459_shorelin_equipment',
    data: {
        name: 'GoPro Action Camera',
        sku: 'GPR-11',
        category: Now.ID['cat_tech'],
        location: Now.ID['loc_south_jetty'],
        description: 'GoPro with SD card, floating grip, and chest mount.',
        total_quantity: 4,
        available_quantity: 4,
        hourly_rate: 10,
        half_day_rate: 25,
        full_day_rate: 45,
        deposit: 150,
        replacement_cost: 450,
        condition: 'good',
        requires_waiver: true,
    },
})
Record({
    $id: Now.ID['eq_metal_detector'],
    table: 'x_1939459_shorelin_equipment',
    data: {
        name: 'Metal Detector',
        sku: 'MET-DET',
        category: Now.ID['cat_tech'],
        location: Now.ID['loc_north_cove'],
        description: 'Beach metal detector — find treasure (or car keys).',
        total_quantity: 3,
        available_quantity: 3,
        hourly_rate: 8,
        half_day_rate: 18,
        full_day_rate: 30,
        deposit: 50,
        replacement_cost: 250,
        condition: 'good',
    },
})

// ---------- Wheels ----------
Record({
    $id: Now.ID['eq_cruiser_bike'],
    table: 'x_1939459_shorelin_equipment',
    data: {
        name: 'Beach Cruiser Bike',
        sku: 'BIK-CRS',
        category: Now.ID['cat_wheels'],
        location: Now.ID['loc_main_pier'],
        description: 'Single-speed beach cruiser with basket. Helmet included.',
        total_quantity: 15,
        available_quantity: 15,
        hourly_rate: 10,
        half_day_rate: 22,
        full_day_rate: 35,
        weekly_rate: 150,
        deposit: 75,
        replacement_cost: 400,
        condition: 'good',
        requires_waiver: true,
    },
})

// ---------- Sunset & Evening ----------
Record({
    $id: Now.ID['eq_hammock'],
    table: 'x_1939459_shorelin_equipment',
    data: {
        name: 'Double Hammock with Stand',
        sku: 'HMK-DBL',
        category: Now.ID['cat_evening'],
        location: Now.ID['loc_north_cove'],
        description: 'Double hammock with portable sand stand.',
        total_quantity: 6,
        available_quantity: 6,
        half_day_rate: 15,
        full_day_rate: 25,
        weekly_rate: 90,
        deposit: 30,
        replacement_cost: 160,
        condition: 'good',
    },
})
Record({
    $id: Now.ID['eq_bonfire_kit'],
    table: 'x_1939459_shorelin_equipment',
    data: {
        name: 'Beach Bonfire Kit',
        sku: 'BON-KIT',
        category: Now.ID['cat_evening'],
        location: Now.ID['loc_north_cove'],
        description: 'Portable fire pit, firewood, matches, s\u2019mores kit for 6.',
        total_quantity: 5,
        available_quantity: 5,
        full_day_rate: 60,
        deposit: 50,
        replacement_cost: 180,
        condition: 'good',
        requires_waiver: true,
        weather_sensitive: true,
    },
})
