import fs from 'fs/promises';
import path from 'path';
import archiver from 'archiver';
import { v4 as uuid } from 'uuid';
import { ensureExportDir, getExportPath } from '../storage/store.js';
import type { Analysis, ExportConfig, ExportResult, FileNode, Recommendation } from '../../../shared/types.js';

export async function generateProject(
  analysis: Analysis,
  config: ExportConfig
): Promise<ExportResult> {
  const exportId = uuid();
  const exportDir = await ensureExportDir(exportId);
  const projectDir = path.join(exportDir, config.appName || 'servicenow-app');

  // Create directory structure
  await fs.mkdir(path.join(projectDir, 'src', 'fluent', 'generated'), { recursive: true });
  await fs.mkdir(path.join(projectDir, 'src', 'server'), { recursive: true });
  if (hasUIRecommendations(analysis)) {
    await fs.mkdir(path.join(projectDir, 'src', 'client', 'components'), { recursive: true });
  }

  // Generate now.config.json
  await fs.writeFile(
    path.join(projectDir, 'now.config.json'),
    JSON.stringify(
      {
        scope: config.scope,
        scopeId: uuid().replace(/-/g, ''),
        name: config.appName,
      },
      null,
      4
    )
  );

  // Generate package.json
  const pkgJson: Record<string, unknown> = {
    name: config.appName.toLowerCase().replace(/\s+/g, '-') + '-sample',
    version: '1.0.0',
    description: config.description,
    scripts: {
      build: 'now-sdk build',
      deploy: 'now-sdk install',
    },
    devDependencies: {
      '@servicenow/glide': 'catalog:',
      '@servicenow/sdk': 'catalog:',
      typescript: 'catalog:',
    },
  };

  if (hasUIRecommendations(analysis)) {
    pkgJson.scripts = {
      ...(pkgJson.scripts as object),
      dev: 'now-sdk run dev',
      transform: 'now-sdk transform',
    };
    (pkgJson.devDependencies as Record<string, string>)['@servicenow/isomorphic-rollup'] = 'catalog:';
    if (config.framework === 'React') {
      (pkgJson as Record<string, unknown>).dependencies = {
        react: '^19.0.0',
        'react-dom': '^19.0.0',
      };
      (pkgJson.devDependencies as Record<string, string>)['@types/react'] = '^19.0.0';
      (pkgJson.devDependencies as Record<string, string>)['@types/react-dom'] = '^19.0.0';
    }
  }

  await fs.writeFile(path.join(projectDir, 'package.json'), JSON.stringify(pkgJson, null, 4));

  // Generate tsconfig.json
  await fs.writeFile(
    path.join(projectDir, 'tsconfig.json'),
    JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          module: 'ESNext',
          moduleResolution: 'bundler',
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
        },
        include: ['src'],
      },
      null,
      4
    )
  );

  // Generate placeholder keys.ts
  await fs.writeFile(
    path.join(projectDir, 'src', 'fluent', 'generated', 'keys.ts'),
    `// Auto-generated by now-sdk build\n// Run 'now-sdk build' to populate this file\nexport {}\n`
  );

  // Write accepted recommendations as source files
  const allRecs = Object.values(analysis.recommendations).flat();
  const accepted = allRecs.filter((r) => r.status === 'accepted' || r.status === 'edited');

  for (const rec of accepted) {
    const code = rec.editedCode || rec.targetCode;
    const fileName = generateFileName(rec);

    if (rec.category === 'Business Rules' || rec.category === 'Script Includes') {
      // Check if the code has server module imports — split if needed
      if (code.includes("from '@servicenow/glide'") || code.includes('GlideRecord')) {
        await fs.writeFile(path.join(projectDir, 'src', 'server', fileName.replace('.now.ts', '.ts')), code);
      } else {
        await fs.writeFile(path.join(projectDir, 'src', 'fluent', fileName), code);
      }
    } else if (rec.category === 'UI Pages') {
      await fs.writeFile(path.join(projectDir, 'src', 'fluent', fileName), code);
    } else {
      await fs.writeFile(path.join(projectDir, 'src', 'fluent', fileName), code);
    }
  }

  // Build output file tree
  const fileTree = await buildExportTree(projectDir, projectDir);

  return { exportId, fileTree };
}

export async function createZipStream(exportId: string): Promise<archiver.Archiver> {
  const exportDir = getExportPath(exportId);
  // Verify the export directory exists
  await fs.access(exportDir);

  const archive = archiver('zip', { zlib: { level: 9 } });
  const entries = await fs.readdir(exportDir);

  for (const entry of entries) {
    const fullPath = path.join(exportDir, entry);
    const stat = await fs.stat(fullPath);
    if (stat.isDirectory()) {
      archive.directory(fullPath, entry);
    } else {
      archive.file(fullPath, { name: entry });
    }
  }

  archive.finalize();
  return archive;
}

function hasUIRecommendations(analysis: Analysis): boolean {
  return analysis.recommendations['UI Pages'].some(
    (r) => r.status === 'accepted' || r.status === 'edited'
  );
}

function generateFileName(rec: Recommendation): string {
  const base = rec.targetName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');

  switch (rec.category) {
    case 'Tables':
      return `${base}.now.ts`;
    case 'Business Rules':
      return `${base}-rules.now.ts`;
    case 'REST APIs':
      return `${base}-api.now.ts`;
    case 'Script Includes':
      return `${base}.now.ts`;
    case 'UI Pages':
      return `${base}-page.now.ts`;
    case 'Service Catalog':
      return `${base}-catalog.now.ts`;
    default:
      return `${base}.now.ts`;
  }
}

async function buildExportTree(dir: string, base: string): Promise<FileNode[]> {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const nodes: FileNode[] = [];

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    const relPath = path.relative(base, fullPath);

    if (entry.isDirectory()) {
      const children = await buildExportTree(fullPath, base);
      nodes.push({ name: entry.name, type: 'folder', path: relPath, children, fileCount: children.length });
    } else {
      nodes.push({ name: entry.name, type: 'file', path: relPath });
    }
  }

  return nodes;
}
